### ISSUE TITLE
Extension not working correctly

### ISSUE THREAD

**Issue by Hyperbuilder** [evenaven/discode#1]
![image](https://user-images.githubusercontent.com/67744001/104763520-50deee00-5766-11eb-9ef7-4ab06411894d.png)

If I try to share the code on the left i get an Error, see rightside.
I tried re-Installing the extension to its most recent version (**v1.1.1**).
Need any additional Information just DM me on dc or ask here

Greeting HyperBuilder

**Comment by evenaven** [comment]
Use the "Set a Webhook" command through the Command Palette to reconfigure it, using it checks for any invalid input, if it still errors out let me know.

**Comment by Hyperbuilder** [comment]
Reconfiguring it still gives exactly the same Error as before. 
Doesnt give me invalid input warnings

**Comment by evenaven** [comment]
Alright, I'll look into it tomorrow and let you know if I manage to fix it.

**Comment by evenaven** [comment]
I've found the issue! The module I use to generate Hastebin links is breaking, it used to work before and when I released the 1.1.0 update, but it looks like it's too outdated now. I'm going to be looking into alternatives and I'll let you know how it goes.

**Comment by evenaven** [comment]
In release 1.1.2 I've removed the ability to share long code with Hastebin (this is planned to be temporary), and made it so if code is under 2000 characters it can still be shared to Discord. I'll look into Hastebin alternatives or fixes for a future update and bring the feature back.

**Comment by evenaven** [comment]
If the Hastebin feature is not the issue, please let me know.
