### ISSUE TITLE
Suggestion to add support for Webhooks created in Discord Canary

### ISSUE THREAD

**Issue by limited-dev** [evenaven/discode#2]
It might be a good idea to add support for webhooks created in Canary.
Currently if you try it displays this:

![image](https://user-images.githubusercontent.com/74376181/105013492-9a1d8f00-5a3f-11eb-9b60-9d4b0f0e7e58.png)

(You can still create webhooks in Canary, you only have to remove the "canary." part of the url.)

**Comment by HiItsDevin** [comment]
probably should do the same for the PTB prefix too

**Comment by limited-dev** [comment]
Yeh. I might code it myself and create a pull request (or push? idk how this page works really xD)

**Comment by evenaven** [comment]
Fixed in Release 1.1.3
